import { openDB } from 'idb';
import { z } from 'zod';
import type { Profile, Garment, SavedLook, Analysis } from '../../shared/types';
export interface AppState { profile: Profile; garments: Garment[]; saved: SavedLook[] }
export const defaultAvatar = { height: 175, build: 0.5, shoulders: 0.5, skinTone: '#b98260', hairColor: '#211914', hairStyle: 'short' as const, presentation: 'masculine' as const };
export const defaultState = (): AppState => ({profile:{name:'',mood:'Effortless',presentation:'masculine',avatar:{...defaultAvatar},consent:false,onboardingDone:false},garments:[],saved:[]});
const db = () => openDB('vibecheck-device',1,{upgrade(d){d.createObjectStore('app')}});
export async function readState():Promise<AppState>{const d=await db();return (await d.get('app','state')) ?? defaultState()}
export async function writeState(state:AppState){const d=await db();await d.put('app',state,'state')}
const image=z.string().max(12000000).refine(s=>/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s)||/^\/assets\/[a-zA-Z0-9._-]+(?:#\d)?$/.test(s),'Invalid image');
const color=z.string().regex(/^#[0-9a-f]{6}$/i);
const avatar=z.object({height:z.number().min(145).max(205),build:z.number().min(0).max(1),shoulders:z.number().min(0).max(1),skinTone:color,hairColor:color,hairStyle:z.enum(['short','medium','long']),presentation:z.enum(['masculine','feminine','neutral'])});
const analysis=z.object({score:z.number().min(0).max(100),verdict:z.string().max(200),summary:z.string().max(3000),metrics:z.array(z.object({label:z.string(),score:z.number().min(0).max(100),detail:z.string()})).max(10),tips:z.array(z.string()).max(20),callouts:z.array(z.object({label:z.string(),detail:z.string(),x:z.number().min(0).max(100),y:z.number().min(0).max(100)})).optional(),hairstyles:z.array(z.object({name:z.string(),description:z.string()})).optional(),captions:z.array(z.string()).optional(),source:z.enum(['gemini','bedrock','example','manual'])});
const schema=z.object({version:z.literal(1),state:z.object({profile:z.object({name:z.string().max(80),mood:z.string().max(80),presentation:z.enum(['masculine','feminine','neutral']),avatar,photo:image.optional(),bodyPhoto:image.optional(),consent:z.boolean(),onboardingDone:z.boolean()}),garments:z.array(z.object({id:z.string(),name:z.string().max(120),category:z.enum(['tops','bottoms','layers','shoes','accessories']),color,image,createdAt:z.number(),notes:z.string().max(1000).optional()})).max(500),saved:z.array(z.object({id:z.string(),kind:z.enum(['story','loox','outfit']),title:z.string().max(200),image,secondaryImage:image.optional(),analysis,createdAt:z.number(),garmentIds:z.array(z.string()).optional(),avatar:avatar.optional()})).max(500)})});
export function validateBackup(value:unknown):AppState {return schema.parse(value).state}
export const uid=()=>crypto.randomUUID();
export const exampleAnalysis:Analysis={score:92,verdict:'POST IT.',summary:'Clean lines. A relaxed, confident feel.',metrics:[{label:'Mood',score:94,detail:'The natural expression keeps it effortless.'},{label:'Framing',score:86,detail:'Bring the crop a little closer.'},{label:'Clarity',score:91,detail:'Good light lets the details speak.'}],tips:['Try a closer crop to put the focus on you.','Keep the edit light. The natural colours work.'],captions:['Good days, good company.','A little less rush.','Right here, right now.'],source:'example'};
export const exampleLoox:Analysis={score:93,verdict:'LOOKING SHARP.',summary:'A textured crop works with your current look.',metrics:[{label:'Styling',score:93,detail:'Natural volume gives the style movement.'},{label:'Balance',score:90,detail:'A little shape at the sides brings focus up.'},{label:'Versatility',score:88,detail:'Easy to wear with a relaxed finish.'}],tips:['Try a matte finish for light, natural texture.','Ask your barber for a gradual blend at the sides.'],callouts:[{label:'Natural volume',detail:'Keep some height through the crown.',x:50,y:15},{label:'Clean sides',detail:'A gradual blend adds shape.',x:32,y:33},{label:'Light stubble',detail:'A neat outline complements the look.',x:59,y:54}],hairstyles:[{name:'Textured crop',description:'Shorter sides with natural movement on top.'},{name:'Side part',description:'A clean part with a little volume.'},{name:'Natural waves',description:'Keep the length and work with your texture.'}],source:'example'};
export function sampleGarments():Garment[]{return [['Linen shirt','tops','#e6dfcf'],['Navy overshirt','layers','#243448'],['Olive trousers','bottoms','#73735a'],['Brown loafers','shoes','#624332'],['Everyday watch','accessories','#8b6b49'],['Canvas tote','accessories','#d9d0ba']].map(([name,category,color],i)=>({id:`sample-${i}`,name,category:category as Garment['category'],color,image:`/assets/garments.png#${i}`,createdAt:Date.now()}))}
