import {lazy,Suspense,useEffect,useRef,useState,type CSSProperties} from 'react';
import {Link} from 'react-router-dom';
import {ArrowLeft,ArrowRight,Check,Heart,House,UserRound,Play,Pause,RotateCcw,Maximize,Plus,ShieldCheck,LockKeyhole,Sparkles,VolumeX} from 'lucide-react';
import {GarmentImage} from '../components/ui';
import {defaultAvatar,sampleGarments} from '../lib/storage';
import {chapters,chapterAt,clampTime,DEMO_DURATION} from './timeline';
import './demo.css';
import {useRecording} from './useRecording';
const AvatarViewer=lazy(()=>import('../components/AvatarViewer'));
const clothes=sampleGarments();
const male='/assets/portrait-v2.png',female='/assets/demo-female-portrait.png';
const fmt=(n:number)=>`${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,'0')}`;
function Meter({label,value,light=false}:{label:string;value:number;light?:boolean}){return <div className={`demo-meter ${light?'light':''}`}><span>{label}</span><div><i style={{width:`${value}%`}}/></div><b>{value}</b></div>}
function Plate({score,label='Your vibe'}:{score:number;label?:string}){return <div className="demo-plate"><span>{label}</span><strong>{score}<small>/100</small></strong></div>}
function Action({children,onClick,secondary=false}:{children:React.ReactNode;onClick:()=>void;secondary?:boolean}){return <button className={`demo-action ${secondary?'secondary':''}`} onClick={onClick}>{children}{!secondary&&<ArrowRight size={17}/>}</button>}
function DemoPhone({scene,elapsed,advance,playing}:{scene:string;elapsed:number;advance:(id:string)=>void;playing:boolean}){
 const [choice,setSelected]=useState(1),[detail,setDetail]=useState(''),[saved,setSaved]=useState(false),[category,setCategory]=useState('All'),[chosen,setChosen]=useState([0,2,3,4]);
 useEffect(()=>{setSelected(1);setDetail('');setSaved(false);setCategory('All')},[scene]);
 const selected=playing&&scene==='compare'?(elapsed<3?0:1):playing&&scene==='loox'?(elapsed<10?0:elapsed<20?1:2):playing&&scene==='outfit'?(elapsed<10?1:0):choice;
 const soft=scene==='expression', portrait=soft?female:male;
 const home=['intro','home','outro','expression'].includes(scene);
 const next=()=>advance(scene==='story'?'compare':scene==='compare'?'loox':scene==='loox'?'wardrobe':scene==='wardrobe'?'outfit':'story');
 const filtered=clothes.slice(0,5).map((garment,index)=>({garment,index})).filter(({garment})=>category==='All'||garment.category===category.toLowerCase());
 return <section className={`demo-phone ${soft?'soft':''}`} aria-label={`${scene} sample workflow`}>
  <header className="demo-phone-header">{home?<img src="/brand/logo.svg" alt="vibecheck."/>:<><button onClick={()=>advance('home')} aria-label="Demo home"><ArrowLeft size={21}/></button><strong>{scene==='loox'?'loox':scene==='wardrobe'||scene==='outfit'?'ChicFit':scene==='privacy'?'Your space':'Story Check'}</strong></>}<span className="demo-avatar"><img src={portrait} alt="Sample profile"/></span></header>
  <div className="demo-phone-content" key={scene}>
  {home&&<><h2>Good taste.<br/>All you.</h2><p className="demo-subtitle">Look good. Feel right. Be you.</p><div className="demo-segments">{['Story','loox','ChicFit'].map((s,i)=><button className={i===0?'active':''} key={s} onClick={()=>advance(['story','loox','wardrobe'][i])}>{s}</button>)}</div><div className="demo-home-photo"><img src={soft?'/assets/demo-female-hero.png':'/assets/hero-v2.png'} alt="Sample portrait with YOUR VIBE typography"/><div className="demo-sticker">{soft?'So you. So good.':'LOOKING\nSHARP.'}</div></div><Action onClick={next}>Check my story</Action><Action secondary onClick={()=>advance('compare')}>Compare two photos</Action><div className="demo-shortcuts"><button onClick={()=>advance('loox')}><div><b>loox</b><small>Find your<br/>next look</small></div><img src={portrait} alt=""/></button><button onClick={()=>advance('wardrobe')}><div><b>ChicFit</b><small>Style what<br/>you own</small></div><GarmentImage garment={clothes[0]}/></button></div></>}
  {scene==='story'&&<><div className="demo-segments slim"><span>Story Check</span><button className="active">Story</button><button onClick={()=>setDetail('Post selected · the same feedback, ready for your feed.')}>Post</button></div><div className="demo-result-photo"><img src={male} alt="Sample sunset portrait"/><b className="demo-photo-comment">OWN THE<br/>MOMENT.</b>{elapsed<4&&<div className="demo-scan"><Sparkles/><span>Replaying a sample check</span></div>}</div><section className={`demo-ticket ${elapsed>=4?'revealed':''}`}><Plate score={elapsed<4?0:92}/><h3>POST IT.</h3><b>Warm light. Effortlessly you.</b><p>Try a closer crop.</p><hr/>{[['Mood',94],['Framing',86],['Clarity',91]].map(([l,v])=><Meter key={l} label={String(l)} value={elapsed>=6?Number(v):0}/>)}<div className="demo-feedback"><span>Good mood<br/><b>Just right</b></span><span>Framing<br/><b>One small tweak</b></span></div></section><Action onClick={next}>Try this crop</Action></>}
  {scene==='compare'&&<><h2>Same you.<br/>Clearer choice.</h2><div className="demo-comparison">{[0,1].map(i=><button className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={i}><img src={male} style={i?{transform:'scale(1.17)',objectPosition:'55% 45%'}:undefined} alt={i?'Closer crop':'Original portrait'}/><span>{i?'Closer crop':'Original'}</span>{selected===i&&<Check size={19}/>}</button>)}</div><div className="demo-recommend"><img src="/brand/icon.svg" alt=""/><div><b>{selected?'This one’s your vibe.':'Keep the wider view.'}</b><p>{selected?'Warmer light. More focus on you.':'More room for the setting.'}</p></div></div><section className="demo-style-match"><span>Your style match</span><div><strong>89<small>%</small></strong><p>Matches your<br/>recent posts</p><img src={male} alt="Sample style reference"/></div></section><div className="demo-compare-meters"><Meter label="Warmth A" value={72} light/><Meter label="Warmth B" value={94}/><Meter label="Framing A" value={68} light/><Meter label="Framing B" value={93}/></div><Action onClick={()=>{setSaved(true);setDetail('Photo saved in this demo. Continue to loox.')}}>{saved?'Photo saved':'Use this photo'}</Action><Action secondary onClick={next}>Explore loox</Action></>}
  {scene==='loox'&&<><h2>Your look. Your energy.</h2><p className="demo-subtitle">Small details. Still you.</p><div className="demo-loox-photo"><img src={male} alt="Sample portrait with styling annotations"/>{[{text:'Natural volume',x:4,y:5,tip:'Keep some height through the crown.'},{text:'Textured finish',x:72,y:9,tip:'A matte finish keeps texture light.'},{text:'Clean sides',x:3,y:43,tip:'A gradual blend gives the hair shape.'},{text:'Light stubble',x:73,y:71,tip:'A neat outline complements the look.'}].map((c,i)=><button key={c.text} className={`demo-callout c${i} ${elapsed>i*1.5?'visible':''}`} style={{left:`${c.x}%`,top:`${c.y}%`}} onClick={()=>setDetail(c.tip)}>{c.text}<i/></button>)}<div className="demo-sticker">LOOKING<br/>SHARP.</div></div><div className="demo-loox-score"><div><span>Style match</span><strong>93%</strong></div><b>A textured crop<br/>works well.</b></div><div className="demo-row"><h3>Try a hairstyle</h3><small>Inspiration</small></div><div className="demo-hair">{['Original','Textured crop','Side part'].map((s,i)=><button key={s} onClick={()=>{setSelected(i);setDetail(`${s} selected · illustrative hairstyle inspiration.`)}} className={selected===i?'selected':''}><div style={{backgroundImage:'url(/assets/hairstyles-v2.png)',backgroundPosition:`${i*50}% center`}}/><span>{s}</span>{selected===i&&<Check size={14}/>}</button>)}</div><Action onClick={()=>{setSaved(true);setDetail('Look saved in this demo.')}}>{saved?'Look saved':'Save this look'}</Action></>}
  {scene==='wardrobe'&&<><h2>Your wardrobe.<br/>More possibilities.</h2><p className="demo-subtitle">Build looks from what you own.</p><div className="demo-categories">{['All','Tops','Bottoms','Layers','Shoes'].map(s=><button key={s} className={category===s?'active':''} onClick={()=>setCategory(s)}>{s}</button>)}</div><div className="demo-garments">{filtered.map(({garment,index})=><button className={chosen.includes(index)?'chosen':''} key={garment.id} onClick={()=>setChosen(v=>v.includes(index)?v.filter(n=>n!==index):[...v,index])}><GarmentImage garment={garment}/><span>{garment.name}</span>{chosen.includes(index)&&<Check size={14}/>}</button>)}<button className="demo-add" onClick={()=>setDetail('Add your own clothing photos in the main app. Demo pieces are already loaded.')}><Plus/><span>Add clothes</span></button></div><div className="demo-model-card"><img src="/assets/portrait.png" alt="Style reference, not a generated 3D scan"/><div><h3>Your style model</h3><p>A 3D prototype to<br/>explore combinations.</p><b>START WITH<br/>WHAT YOU OWN.</b></div></div><Action onClick={next}>Build an outfit</Action></>}
  {scene==='outfit'&&<><h2>Same pieces.<br/>New energy.</h2><div className="demo-segments"><button className={selected===1?'active':''} onClick={()=>setSelected(1)}>Casual dinner</button><button className={selected===0?'active':''} onClick={()=>setSelected(0)}>Relaxed</button></div><div className="demo-three"><Suspense fallback={<p>Opening the 3D prototype…</p>}><AvatarViewer params={defaultAvatar} garments={selected?clothes.filter((_,i)=>[0,2,3,4].includes(i)):clothes.filter((_,i)=>[1,2,3].includes(i))} autoRotate={playing}/></Suspense><span className="demo-prototype-label">Working 3D prototype · not a personal scan</span></div><h4>Tap a mood to swap the combination</h4><div className="demo-outfit-pieces">{clothes.slice(0,5).map(g=><GarmentImage key={g.id} garment={g}/>)}</div><div className="demo-fit-ticket"><Plate score={88} label="Sample fit"/><div><h3>WEAR IT.</h3><p>Easy layers. Strong colour story.</p></div></div><Action onClick={()=>{setSaved(true);setDetail('Outfit saved in this demo.')}}>{saved?'Outfit saved':'Save outfit'}</Action><p className="demo-small-note">Personal photo-to-3D and fitted clothing: future work.</p></>}
  {scene==='privacy'&&<PrivacyProof elapsed={elapsed}/>}
  {detail&&<button className="demo-toast" role="status" onClick={()=>setDetail('')}><Check size={17}/>{detail}</button>}
  </div><nav className="demo-phone-nav" aria-label="Demo navigation"><button className="active" onClick={()=>advance('home')}><House size={21}/>Home</button><button onClick={()=>setDetail(saved?'Your sample look is saved for this demo.':'Save a photo, look or outfit during the demo.')}><Heart size={21}/>Saved</button><button onClick={()=>advance('privacy')}><UserRound size={21}/>Me</button></nav>
 </section>
}
function PrivacyProof({elapsed}:{elapsed:number}){
 const [proof,setProof]=useState<{enabled:{allowed:boolean;version:string};paused:{allowed:boolean};generation:{allowed:boolean}}|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/privacy/proof',{signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(setProof).catch(e=>{if(e.name!=='AbortError')setFailed(true)});return()=>controller.abort()},[]);
 const paused=elapsed>=5;
 return <div className="demo-privacy"><ShieldCheck size={52}/><h2>Your space.<br/>Your rules.</h2><p>Keep your wardrobe close.<br/>Choose when your photos go to AI.</p><div className="demo-policy-state"><LockKeyhole/><b>{paused?'Photo processing paused':'Photo processing enabled'}</b><span>{failed?'Local API unavailable':!proof?'Checking the policy…':paused?(proof.paused.allowed?'Unexpected permission':'Cedar decision: DENY'):(proof.enabled.allowed?'Cedar decision: ALLOW':'Unexpected denial')}</span></div><div className="demo-policy-detail"><strong>AWS open source</strong><h3>Cedar</h3><p>Runs on this machine.<br/>No AWS account. No cloud bill.</p>{proof&&<small>Live engine v{proof.enabled.version}<br/>Image-generation policy: {proof.generation.allowed?'allowed':'blocked'}</small>}</div><p className="demo-small-note">Live policy dry run. No photos sent, no provider calls. Your actual preference is unchanged.</p><Link className="demo-action secondary" to="/profile">Open real privacy controls <ArrowRight size={17}/></Link></div>
}
export default function Demo(){
 const initial=clampTime(Number(new URLSearchParams(location.search).get('t')||0));
 const [time,setTime]=useState(initial),[playing,setPlaying]=useState(false),[clean,setClean]=useState(false);
 const frame=useRef(0),last=useRef(0),root=useRef<HTMLDivElement>(null);const chapter=chapterAt(time);
 const [reduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches||new URLSearchParams(location.search).has('still'));
 const recording=useRecording(()=>{setTime(0);last.current=performance.now();setClean(true);setPlaying(true)},()=>{setPlaying(false);setClean(false)});
 useEffect(()=>{if(!playing)return;last.current=performance.now();function tick(now:number){const delta=(now-last.current)/1000;last.current=now;setTime(t=>clampTime(t+delta));frame.current=requestAnimationFrame(tick)}frame.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame.current)},[playing]);
 useEffect(()=>{if(time>=DEMO_DURATION){setPlaying(false);recording.stop()}},[time]);
 const seek=(n:number)=>{setTime(clampTime(n));last.current=performance.now()};
 const jump=(id:string)=>{const c=chapters.find(c=>c.id===id);if(c){setPlaying(false);seek(c.start)}};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement||e.target instanceof HTMLAnchorElement)return;if(e.code==='Space'){e.preventDefault();setPlaying(p=>!p)}if(e.key==='Escape')setClean(false);if(e.key==='ArrowRight'){e.preventDefault();setTime(t=>clampTime(t+5))}if(e.key==='ArrowLeft'){e.preventDefault();setTime(t=>clampTime(t-5))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{['/assets/hero-v2.png',male,'/assets/demo-female-hero.png',female,'/assets/demo-female-outfit.png','/assets/garments-soft.png','/assets/score-plate-v2.png'].forEach(src=>{const i=new Image();i.src=src})},[]);
 return <div ref={root} className={`demo-stage ${clean?'clean':''} ${reduced?'reduced-motion':''} ${playing?'is-playing':'is-paused'}`} style={{'--progress':`${time/DEMO_DURATION*100}%`} as CSSProperties}>
  <header className="demo-brandbar"><Link to="/"><img src="/brand/logo.svg" alt="vibecheck home"/></Link><span>FIRST COMMIT / BEST UI</span><div><VolumeX size={14}/> Captioned walkthrough · 2:58</div></header>
  <main className="demo-composition"><section className="demo-editorial" key={chapter.id}><span className="demo-kicker">{chapter.kicker}</span><h1>{chapter.title}</h1><p>{chapter.copy}</p><div className="demo-chapter-count"><span>{String(chapters.indexOf(chapter)+1).padStart(2,'0')}</span><i/>10</div><div className="demo-facts">{chapter.id==='privacy'?<><ShieldCheck/><span>Real policy evaluation<br/><b>Zero cloud calls</b></span></>:<><img src="/brand/icon.svg" alt=""/><span>LOOK GOOD.<br/>FEEL RIGHT.<br/>BE YOU.</span></>}</div></section>
   <div className="demo-device-wrap"><DemoPhone scene={chapter.id} elapsed={time-chapter.start} advance={jump} playing={playing&&!reduced}/><div className="demo-source">{chapter.id==='privacy'?'LIVE LOCAL POLICY · NO PHOTO SENT':chapter.id==='outfit'?'INTERACTIVE PROTOTYPE · SAMPLE OUTFIT':'SAMPLE PHOTOS & ILLUSTRATIVE RESULTS'}</div></div>
   <aside className="demo-side-note" key={`side-${chapter.id}`}><span>DESIGNED TO FEEL LIKE YOU</span>{chapter.id==='expression'?<img className="demo-fashion-photo" src="/assets/demo-female-outfit.png" alt="Illustrative outfit concept, not a 3D scan"/>:<img src="/assets/score-plate-v2.png" alt=""/>}<p>{chapter.id==='expression'?'One system.\nMore self-expression.':chapter.id==='outfit'?'Drag. Rotate.\nExplore a combination.':'A clear next step.\nA little more confidence.'}</p></aside>
  </main>
  <div className="demo-caption" aria-live={playing?'off':'polite'}>{chapter.caption}</div>
  <footer className="demo-controls"><button className="demo-record" onClick={()=>void (recording.recording?recording.stop():recording.start())}>{recording.recording?'Stop recording':'Record'}</button><button onClick={()=>{if(time>=DEMO_DURATION)seek(0);setPlaying(p=>!p)}} aria-label={playing?'Pause demo':'Play demo'}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><button onClick={()=>{seek(0);setPlaying(false)}} aria-label="Restart demo"><RotateCcw size={18}/></button><span className="demo-clock">{fmt(time)} / 2:58</span><input type="range" aria-label="Demo timeline" min={0} max={DEMO_DURATION} step={.1} value={time} onChange={e=>seek(Number(e.target.value))}/><button onClick={()=>setClean(c=>!c)} aria-label="Toggle clean recording view"><Maximize size={18}/></button><Link to="/">Explore app <ArrowRight size={15}/></Link></footer>
  {recording.error&&<p className="demo-record-message" role="status">{recording.error}</p>}<nav className="demo-chapters" aria-label="Demo chapters">{chapters.map((c,i)=><button key={c.id} aria-current={chapter.id===c.id?'step':undefined} onClick={()=>jump(c.id)}>{String(i+1).padStart(2,'0')} {c.id==='expression'?'Style 2':c.id}</button>)}</nav>
  {clean&&<button className="demo-exit-clean" onClick={()=>setClean(false)}>Show controls</button>}
 </div>
}
