import {useRef,useState,useEffect,type ReactNode,type ButtonHTMLAttributes} from 'react';
import {ArrowLeft,ArrowRight,Upload,Camera,X,LoaderCircle,AlertCircle,Check,Bookmark,Sparkles} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {readImage} from '../lib/images';
import {useStore} from '../lib/context';
import {getConfig,type CloudConfig} from '../lib/cloud';
import type {Analysis,Garment} from '../../shared/types';
export function Button({children,secondary=false,loading=false,className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{secondary?:boolean;loading?:boolean}){return <button {...props} disabled={props.disabled||loading} className={`${secondary?'btn secondary':'btn'} ${className}`}>{loading?<LoaderCircle className="spin" size={18}/>:null}{children}</button>}
export function PageHeading({title,subtitle,back,actions}:{title:string;subtitle?:string;back?:string;actions?:ReactNode}){const nav=useNavigate();return <header className="page-heading">{back&&<button className="back" aria-label="Go back" onClick={()=>nav(back)}><ArrowLeft size={19}/></button>}<div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{actions&&<div className="heading-actions">{actions}</div>}</header>}
export function PhotoPicker({onPick,children,className='',camera=false}:{onPick:(s:string)=>void;children?:ReactNode;className?:string;camera?:boolean}){const ref=useRef<HTMLInputElement>(null);const {notify}=useStore();const [busy,setBusy]=useState(false);const accept=async(file?:File)=>{if(!file)return;setBusy(true);try{onPick(await readImage(file))}catch(e){notify((e as Error).message)}finally{setBusy(false);if(ref.current)ref.current.value=''}};return <><input ref={ref} type="file" hidden accept="image/jpeg,image/png,image/webp" capture={camera?'user':undefined} onChange={e=>void accept(e.target.files?.[0])}/><button type="button" className={`photo-picker ${className}`} onClick={()=>ref.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void accept(e.dataTransfer.files[0])}} disabled={busy}>{busy?<LoaderCircle className="spin"/>:children||<><span className="upload-icon">{camera?<Camera/>:<Upload/>}</span><strong>{camera?'Take a photo':'Add your photo'}</strong><span>JPG, PNG or WebP · up to 12 MB</span><small>or drop it here</small></>}</button></>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>}
export function ErrorPanel({error,onRetry}:{error:string;onRetry?:()=>void}){return <div className="error-panel" role="alert"><AlertCircle size={20}/><div><strong>That didn’t go through.</strong><p>{error}</p>{onRetry&&<button className="text-button" onClick={onRetry}>Try again <ArrowRight size={15}/></button>}</div></div>}
export function Busy({label='Finding your vibe…'}:{label?:string}){return <div className="busy" role="status"><img src="/brand/icon.svg" alt=""/><h3>{label}</h3><p>A little perspective is on its way.</p><div className="progress-track"><span/></div></div>}
export function ScoreTicket({analysis,compact=false}:{analysis:Analysis;compact?:boolean}){return <section className={`score-ticket ${compact?'compact':''}`}><div className="ticket-top"><div className="score-plate"><span>{compact?'Your fit':'Your vibe'}</span><div><b>{Math.round(analysis.score)}</b><small>/100</small></div></div><div className="ticket-verdict"><span className="micro">{analysis.source==='example'?'EXAMPLE RESULT':'YOUR RESULT'}</span><h2>{analysis.verdict}</h2><p>{analysis.summary}</p></div></div><div className="perforation"/>{analysis.metrics.map(m=><div className="metric" key={m.label}><span title={m.detail}>{m.label}</span><div><i style={{width:`${m.score}%`}}/></div><b>{Math.round(m.score)}</b></div>)}{analysis.tips[0]&&<div className="ticket-tip"><Sparkles size={18}/><p><strong>One small move</strong>{analysis.tips[0]}</p></div>}</section>}
export function GarmentImage({garment,className=''}:{garment:Pick<Garment,'image'|'name'>;className?:string}){const [src,cell]=garment.image.split('#');return cell!==undefined?<div role="img" aria-label={garment.name} className={`garment-image ${className}`} style={{backgroundImage:`url("${src}")`,backgroundSize:'300% 200%',backgroundPosition:`${(Number(cell)%3)*50}% ${Math.floor(Number(cell)/3)*100}%`}}/>:<img className={`garment-image ${className}`} src={src} alt={garment.name}/>}
export function ConsentNotice(){const [config,setConfig]=useState<CloudConfig|null>(null);useEffect(()=>{void getConfig().then(setConfig).catch(()=>{})},[]);return <p className="privacy-note">{config?.cloudEnabled?'AI checks upload selected photos to private AWS storage and process them with AWS AI.':'Photos stay on this device until you request a check. AI checks send selected photos to '+(config?.provider==='bedrock'?'AWS':'Google')+'.'} Style feedback is subjective.</p>}
export function EmptyState({icon,heading,copy,children}:{icon?:ReactNode;heading:string;copy:string;children?:ReactNode}){return <div className="empty-state">{icon||<Bookmark size={32}/>}<h2>{heading}</h2><p>{copy}</p>{children}</div>}
export function Pills({items,value,onChange}:{items:string[];value:string;onChange:(s:string)=>void}){return <div className="pills">{items.map(s=><button type="button" key={s} className={s===value?'selected':''} aria-pressed={s===value} onClick={()=>onChange(s)}>{s===value&&<Check size={13}/>} {s}</button>)}</div>}
