(() => {
'use strict';
const {screens,flows}=window.DESIGN;
const byId=new Map(screens.map(s=>[s.id,s]));
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current=byId.get(location.hash.slice(1))||screens[0];
let source='H01';
let savedType='story';
const fileNames={home:'01-home.png','story-result':'02-story-result.png',compare:'03-compare.png',loox:'04-loox.png',wardrobe:'05-wardrobe.png',chicfit:'06-chicfit.png'};
const navItems=[['Home','H01'],['Story Check','S01'],['loox','L01'],['ChicFit','C01'],['Wardrobe','W02'],['Saved','V02']];
const stateText={loading:['Working on it…','Keep the current inputs visible. No invented progress percentage.'],error:["That didn't finish.",'Your inputs are still here. Try again or edit the draft.'],empty:['Nothing here yet.','Start with a photo or an item. Never substitute fabricated user data.'],disabled:['One more step before continuing.','Complete the required fields or choose a supported alternative.'],stale:['This input changed.','Check it again for updated feedback. The old score is no longer current.'],success:['Saved on this device.','A success state requires confirmed persistence.']};
function navigate(id){if(!byId.has(id))return;source=current.id;current=byId.get(id);if(current.id.startsWith('L'))savedType='loox';if(current.id.startsWith('C'))savedType='outfit';if(current.id.startsWith('S'))savedType='story';location.hash=id;$('state').value='default';render();$('announcement').textContent=`${current.id}: ${current.title}`;}
function renderNav(){const query=$('search').value.toLowerCase();const groups=[...new Set(screens.map(s=>s.flow))];$('screen-nav').innerHTML=groups.map(g=>{const items=screens.filter(s=>s.flow===g&&`${s.id} ${s.title} ${s.flow}`.toLowerCase().includes(query));return items.length?`<section class="flow-group"><p class="flow-name">${esc(g)}</p>${items.map(s=>`<a href="#${s.id}" class="screen-link ${s.id===current.id?'active':''}" ${s.id===current.id?'aria-current="page"':''}><span>${s.id}</span>${esc(s.title)}</a>`).join('')}</section>`:''}).join('');}
function renderJourney(){const flow=flows[Number($('journey-select').value)||0];$('journey-steps').innerHTML=flow.ids.map((id,i)=>`<button class="journey-step ${id===current.id?'active':''}" data-go="${id}" title="${esc(byId.get(id).title)}">${i+1}. ${id}</button>`).join('');}
function field(f,i){const id='field-'+current.id+'-'+i;const label=esc(f.label);if(f.type==='checkbox')return `<label class="checkbox" for="${id}"><input id="${id}" type="checkbox" ${f.value==='true'?'checked':''}>${label}</label>`;if(f.type==='select')return `<label for="${id}">${label}<select id="${id}">${f.options.map(o=>`<option ${o===f.value?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;if(f.type==='textarea')return `<label for="${id}">${label}<textarea id="${id}">${esc(f.value)}</textarea></label>`;if(f.type==='file')return `<label for="${id}">${label}<input id="${id}" type="file"><span class="small-note">Documentation control only. This viewer never uploads files.</span></label>`;return `<label for="${id}">${label}<input id="${id}" type="${esc(f.type)}" value="${esc(f.value)}" ${f.type==='range'?'min="0" max="100"':''}></label>`;}
function actionButton(a,i){return `<button type="button" class="pbutton ${i?'secondary':''}" data-action="${i}" ${$('state').value==='disabled'&&i===0?'disabled':''} title="${esc(a.effect)}">${esc(a.label)}</button>`;}
function actions(skipFirst=false){return `<div class="product-actions">${current.actions.map((a,i)=>skipFirst&&i===0?'':actionButton(a,i)).join('')}</div>`;}
function photo(avatar=false){const soft=$('style').value==='soft';const src=avatar?(soft?'female-outfit.png':'male-outfit.png'):(soft?'female-portrait.png':'male-portrait.png');return `<div class="photo-preview ${avatar?'avatar':''}"><img src="media/${src}" alt="${avatar?'Illustrative model appearance':'Example portrait'}"><div class="photo-caption">${avatar?'Illustrative model appearance — not interactive 3D':'Example photo — never a user upload'}</div></div>`;}
function upload(){return `<div class="photo-placeholder"><img src="media/icon.svg" alt=""><strong>Choose a photo</strong><p>JPG, PNG or WebP · up to 12 MB</p><p>Drag and drop, or use the file control.</p></div>`;}
function score(){const value=current.flow==='loox'?'93':current.flow==='ChicFit'?'88':'92';const stale=$('state').value==='stale';return `<div class="ticket"><div class="plate"><b>${stale?'—':value}</b><span>/100<br><small>Example score</small></span></div><h3>${current.flow==='ChicFit'?'WEAR IT.':current.flow==='loox'?'YOUR STYLE.':'POST IT.'}</h3><p>${esc(current.copy)}</p>${(current.flow==='ChicFit'?['Colour','Occasion','Style']:['Mood','Framing','Clarity']).map((m,i)=>`<div class="metric"><span>${m}</span><div class="bar"><i style="width:${stale?0:[94,86,91][i]}%"></i></div><strong>${stale?'—':[94,86,91][i]}</strong></div>`).join('')}<div class="hint">${stale?'Check this updated input before showing a new score.':'One small tweak. Keep the explanation clear and actionable.'}</div></div>`;}
function compare(){return `<div class="compare-pair"><div><div class="photo-preview">${photo(false).match(/<img[^>]+>/)[0]}<div class="photo-caption">A · Original</div></div></div><div><div class="photo-preview selected">${photo(false).match(/<img[^>]+>/)[0]}<div class="photo-caption">B · Preview slot</div></div></div></div><p class="small-note">Construction preview repeats the reference photo to show placement. The product must use the actual compared/generated images.</p>`;}
function itemGrid(){return `<div class="grid-reference"><img src="media/garments.png" alt="Example item photography reference"><p class="photo-caption">Example item photography. These pieces are not inferred from the viewer's style.</p></div><div class="item-list">${['Linen shirt','Navy overshirt','Olive trousers','Brown loafers','Everyday watch','Add clothes'].map((name,i)=>`<button class="item-choice" data-item="${i}">${esc(name)}</button>`).join('')}</div>`;}
function bodyContent(){const fields=`<div class="product-fields">${current.fields.map(field).join('')}</div>`;const notes=`<p class="small-note">${esc(current.rules[0]||'')}</p>`;const mode=$('state').value;
if(mode==='empty'){const intake=current.flow==='Wardrobe'?'W03':current.flow==='loox'?'L01':current.flow==='Your model'?'M01':'S01';return `<div class="workarea one"><div class="photo-placeholder"><img src="media/icon.svg" alt=""><strong>${current.flow==='Wardrobe'?'Start with what you own.':'Start with something of yours.'}</strong><p>No fabricated user records or scores appear in an empty state.</p><button class="pbutton" data-go="${intake}">${current.flow==='Wardrobe'?'Add clothes':'Add a photo'}</button></div></div>`;}
if(mode==='loading'&&current.layout!=='processing')return `<div class="workarea"><div>${photo(current.flow==='Your model'||current.flow==='ChicFit')}</div><div><div class="spinner" aria-label="Loading"></div><h3>Waiting for a real response</h3><p>Your draft stays intact. Scores and generated output appear only after success.</p><button class="pbutton secondary" data-resume="1">Cancel</button></div></div>`;
if(mode==='error')return `<div class="workarea"><div>${current.flow==='Account'||current.flow==='Your space'?fields:photo()}</div><div><h3>Your inputs are still here</h3><p>Retry this operation, or return to its setup without losing the draft.</p><div class="product-actions"><button class="pbutton" data-resume="1">Try again</button><button class="pbutton secondary" data-go="${current.back||'H01'}">Edit inputs</button></div>${notes}</div></div>`;
switch(current.layout){
case 'confirm':return `<div class="confirm-card"><h3>${esc(current.title)}</h3><p>${esc(current.copy)}</p>${fields}${notes}${actions()}</div>`;
case 'empty':return `<div class="workarea one"><div class="photo-placeholder"><img src="media/icon.svg" alt=""><strong>${esc(current.title)}</strong><p>${esc(current.copy)}</p></div>${actions()}${notes}</div>`;
case 'upload':return `<div class="workarea"><div>${upload()}${fields}</div><div><h3>Before you continue</h3><ul class="step-list">${current.rules.slice(0,3).map(r=>`<li>${esc(r)}</li>`).join('')}</ul>${actions()}</div></div>`;
case 'processing':return `<div class="workarea"><div>${photo(current.id.startsWith('M')||current.id.startsWith('C'))}</div><div><div class="spinner" aria-label="Processing"></div><h3>${esc(current.title)}</h3><p>${esc(current.copy)}</p><ul class="step-list"><li>Inputs retained</li><li>Waiting for a real response</li><li>No example score substituted</li></ul>${actions(true)}${notes}</div></div>`;
case 'result':return `<div class="workarea"><div>${photo()}</div><div>${score()}${actions()}</div></div>`;
case 'compare':return `<div class="workarea"><div>${compare()}${fields}</div><div>${current.id==='S11'?score():`<h3>${esc(current.title)}</h3><p>${esc(current.copy)}</p><div class="hint">${esc(current.rules[0])}</div>`}${actions()}</div></div>`;
case 'portrait':return `<div class="workarea"><div>${photo()}<div class="hint">Photo callout positions: see the visual target. Connect labels to normalized photo coordinates, not screen pixels.</div></div><div>${fields}${current.id==='L04'?score():`<h3>${esc(current.title)}</h3><p>${esc(current.copy)}</p>`}${actions()}${notes}</div></div>`;
case 'grid':return `<div class="workarea"><div>${fields}${itemGrid()}</div><div><h3>${esc(current.flow==='Wardrobe'?'Your 3D model':'Your selection')}</h3>${photo(true)}${actions()}${notes}</div></div>`;
case 'avatar':return `<div class="workarea"><div>${photo(true)}<div class="hint"><strong>Drag to rotate</strong><p>Actual 3D renderer required in product. Front / Side / Back / Reset and keyboard rotation remain available.</p></div></div><div>${fields}${current.id==='C04'?score():`<h3>Check your model</h3><p>${esc(current.copy)}</p>`}${actions()}${notes}</div></div>`;
case 'export':return `<div class="workarea"><div>${photo()}</div><div>${fields}<div class="hint">Export the real selected image. No auto-publication or involuntary score overlay.</div>${actions()}${notes}</div></div>`;
case 'detail':return `<div class="workarea"><div>${photo(current.flow==='Saved'&&savedType==='outfit')}</div><div>${fields}<h3>${current.id==='H01'?"What's the move?":esc(current.title)}</h3><p>${esc(current.copy)}</p>${actions()}${notes}</div></div>`;
default:{const profile=['Account','Your space','Recovery'].includes(current.flow);return `<div class="workarea ${profile?'one':''}">${profile?'':`<div>${current.flow==='Your model'?photo(true):photo()}</div>`}<div>${fields}${notes}${actions()}</div></div>`;}
}}
function preview(){const isMobile=$('viewport').value==='mobile';const style=$('style').value;const state=$('state').value;const banner=state==='default'?'':`<div class="state-banner ${state==='loading'?'loading':state==='success'?'success':''}" role="status"><strong>${esc(stateText[state][0])}</strong><p>${esc(stateText[state][1])}</p></div>`;return `<div class="preview ${isMobile?'mobile':''} ${style}"><aside class="product-nav"><img src="media/logo.svg" alt="vibecheck.">${navItems.map(([label,id])=>`<a href="#${id}" class="${current.flow===label||(current.id==='H01'&&label==='Home')?'selected':''}">${label}</a>`).join('')}<a href="#P01">Settings</a></aside><div><div class="product-body"><div class="product-top"><span>${esc(current.flow)} / ${current.id}</span><img src="media/${style==='soft'?'female':'male'}-portrait.png" alt="Example profile"></div><h2>${esc(current.title)}</h2><p class="product-sub">${esc(current.copy)}</p>${banner}${bodyContent()}</div><nav class="product-bottom" aria-label="Mobile navigation"><a href="#H01">Home</a><a href="#V02">Saved</a><a href="#P01">Me</a></nav></div></div>`;}
function render(){renderNav();renderJourney();$('screen-context').textContent=current.flow+' / '+current.id;$('screen-title').textContent=current.title;const isTarget=$('view').value==='target'&&current.visual&&$('state').value==='default';const mobile=$('viewport').value==='mobile';const style=$('style').value;let src;if(isTarget){src=mobile?`visuals/mobile/${style}-${['home','story-result','compare'].includes(current.visual)?'story':'style'}.png`:`visuals/${style==='soft'?'female':'male'}/${fileNames[current.visual]}`;$('screen-canvas').innerHTML=`<a href="${src}" target="_blank" rel="noopener"><img class="target-image" src="${src}" alt="${esc(current.title)} ${style} ${mobile?'mobile reference board':'desktop visual target'}"></a>`;$('canvas-note').textContent=mobile?'Mobile reference board. Choose Construction preview to inspect this screen alone. Written controls and state rules override omitted mockup details.':'High-fidelity desktop visual target. Open image for full size. Choose Construction preview to follow individual controls.';}else{$('screen-canvas').innerHTML=preview();$('canvas-note').textContent='Annotated construction preview. Real controls and hierarchy are specified; images are example assets. This documentation viewer performs no uploads, AI requests or real saving.';}
$('contract-rules').innerHTML=`<ul>${current.rules.map(r=>`<li>${esc(r)}</li>`).join('')}</ul>`;$('contract-layout').innerHTML=`<p><strong>Desktop:</strong> ${esc(current.desktop)}</p><p><strong>Mobile:</strong> ${esc(current.mobile)}</p><p><strong>Back:</strong> ${current.back?`<a href="#${current.back}">${current.back}</a>`:'Root'}; validated returnTo overrides this default.</p>`;
$('contract-actions').innerHTML=current.actions.map((a,i)=>`<a class="action-row" href="#${a.to}" data-action="${i}"><strong>${esc(a.label)} · ${a.to}</strong><p>${esc(a.effect)}</p></a>`).join('');$('contract-fields').innerHTML=current.fields.length?current.fields.map(f=>`<div class="field-row"><strong>${esc(f.label)}</strong> · ${esc(f.type)}${f.options.length?`<p>${esc(f.options.join(' / '))}</p>`:''}</div>`).join(''):'<p>No additional input fields.</p>';
$('simulation').innerHTML=`<span>DOCUMENTATION NAVIGATION</span>${current.back?`<button data-go="${current.back}">Back · ${current.back}</button>`:''}${current.layout==='processing'?`<button data-action="0">Simulate successful completion</button><button data-error="1">Inspect failure</button>`:''}<button id="show-construction">${isTarget?'Inspect construction preview':'Show visual target if available'}</button>`;}
function perform(index){const a=current.actions[index];if(!a)return;$('announcement').textContent=a.effect;let target=a.to;if(current.id==='X01'&&index<2)target=source==='X01'?'S02':source;if(current.id==='V03'&&index===0)target=savedType==='loox'?'L05':savedType==='outfit'?'C04':'S02';if(target===current.id){$('announcement').textContent='Illustrated action: '+a.effect;$('simulation').innerHTML+=`<span class="hint">${esc(a.effect)}</span>`;return;}navigate(target);}
document.addEventListener('click',e=>{if(e.target.closest('[data-resume]')){$('state').value='default';render();return;}const action=e.target.closest('[data-action]');if(action){e.preventDefault();perform(Number(action.dataset.action));return;}const go=e.target.closest('[data-go]');if(go){navigate(go.dataset.go);return;}const item=e.target.closest('[data-item]');if(item){item.classList.toggle('chosen');$('announcement').textContent='Example selection changed; no wardrobe data is saved.';return;}if(e.target.closest('[data-error]')){$('state').value='error';render();return;}if(e.target.id==='show-construction'){$('view').value=$('view').value==='construction'?'target':'construction';render();return;}const link=e.target.closest('a[href^="#"]');if(link&&byId.has(link.hash.slice(1))){e.preventDefault();navigate(link.hash.slice(1));}});
$('search').addEventListener('input',renderNav);['style','viewport','view','state'].forEach(id=>$(id).addEventListener('change',render));$('journey-select').innerHTML=flows.map((f,i)=>`<option value="${i}">${esc(f.name)}</option>`).join('');$('journey-select').addEventListener('change',()=>{const flow=flows[Number($('journey-select').value)];navigate(flow.ids[0]);});window.addEventListener('hashchange',()=>{const next=byId.get(location.hash.slice(1));if(next&&next.id!==current.id){current=next;render();}});render();
})();
